import wandb
import os
import sys
import torch
import torch.nn.functional as F
import argparse
from torch_geometric.loader import DataLoader as PyGDataLoader
from torch_geometric.utils import dropout_adj
from sklearn.model_selection import KFold
from torch.utils.data import DataLoader, ConcatDataset, WeightedRandomSampler, Subset
import numpy as np
from pathlib import Path
import pandas as pd

# --------------------------------------------------
# Local imports
# --------------------------------------------------
root_dir = os.path.abspath(os.path.join(os.getcwd(), ".."))
if root_dir not in sys.path:
    sys.path.append(root_dir)

from src.models.Fakenews_GNN import Fakenews_GNN
from src.utils.data_loader import FNNDataset, add_bot_score_feature

def mask_node_features(data, mask_prob):
    """
    Randomly masks the node features of a subset of nodes.
    mask_prob = probability that a node has ALL its features zeroed.
    """
    if mask_prob <= 0:
        return data

    x = data.x.clone()
    num_nodes = x.size(0)

    # mask vector for nodes (True = mask this node)
    mask_nodes = torch.rand(num_nodes, device=x.device) < mask_prob

    # apply masking
    x[mask_nodes] = 0.0

    data.x = x
    return data


def drop_edges(data, drop_prob):
    """
    Randomly drops edges using PyG dropout_adj.
    drop_prob = probability that an edge is removed.
    """
    if drop_prob <= 0:
        return data

    edge_index, _ = dropout_adj(
        data.edge_index,
        p=drop_prob,
        force_undirected=False,
        num_nodes=data.num_nodes
    )
    data.edge_index = edge_index
    return data

# --------------------------------------------------
# Argument parsing & W&B setup
# --------------------------------------------------
parser = argparse.ArgumentParser()
parser.add_argument("--project", default="fakenews-gnn", type=str)
parser.add_argument("--kfolds", default=5, type=int)
parser.add_argument("--config_csv", default="sweep_configs.csv", type=str,
                    help="CSV with sweep configurations generated by make_configid_sweep.py")
args = parser.parse_args()

wandb.init(project=args.project)
config = wandb.config
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# --------------------------------------------------
# Load config row from CSV if config_id is provided
# --------------------------------------------------
if "config_id" not in config:
    raise ValueError("Missing config_id in W&B config. Run this inside a sweep using make_configid_sweep.py output.")

configs_df = pd.read_csv(args.config_csv)
if config.config_id >= len(configs_df):
    raise ValueError(f"config_id {config.config_id} out of range (max {len(configs_df)-1})")

# Fill wandb.config with parameters from CSV
row = configs_df.iloc[config.config_id]
for col in configs_df.columns:
    wandb.config[col] = row[col]

print(f"Using config row {config.config_id}:\n{dict(config)}")

# --------------------------------------------------
# Dataset loading
# --------------------------------------------------
data_dir = Path("../data/raw/")
gos_map_path = data_dir / "gos_id_twitter_mapping.pkl"
pol_map_path = data_dir / "pol_id_twitter_mapping.pkl"
root = os.path.join(root_dir, "data")

dataset_gos = FNNDataset(root=root, name="gossipcop", feature="profile")
add_bot_score_feature(dataset_gos, gos_map_path, "./scores_gos.json")

dataset_pol = FNNDataset(root=root, name="politifact", feature="profile")
add_bot_score_feature(dataset_pol, pol_map_path, "./scores_pol.json")

dataset = ConcatDataset([dataset_gos, dataset_pol])
len_gos = len(dataset_gos)
len_pol = len(dataset_pol)
weights_gos = torch.ones(len_gos) / len_gos
weights_pol = torch.ones(len_pol) / len_pol
sample_weights = torch.cat([weights_gos, weights_pol])
print("Loaded dataset for cross-validation")

# --------------------------------------------------
# K-Fold setup
# --------------------------------------------------
kf = KFold(n_splits=args.kfolds, shuffle=True, random_state=1312)
fold_results = []

# --------------------------------------------------
# Cross-validation loop
# --------------------------------------------------
for fold, (train_idx, val_idx) in enumerate(kf.split(dataset)):
    print(f"\n========== Fold {fold + 1}/{args.kfolds} ==========")

    train_subset = Subset(dataset, train_idx)
    val_subset   = Subset(dataset, val_idx)

    train_weights = sample_weights[train_idx]

    train_sampler = WeightedRandomSampler(
        weights=train_weights,
        num_samples=len(train_weights),
        replacement=True
    )

    train_loader = PyGDataLoader(
        train_subset,
        batch_size=config.batch_size,
        sampler=train_sampler
    )

    val_loader = PyGDataLoader(
        val_subset,
        batch_size=config.batch_size,
        shuffle=False
    )

    # --------------------------------------------------
    # Model setup
    # --------------------------------------------------
    model = Fakenews_GNN(
        in_channels=11,
        hidden_channels=config.hidden_channels,
        out_channels=2,
        num_layers=config.num_layers,
        conv_type=config.conv_type,
        dropout=config.dropout,
        use_batchnorm=config.use_batchnorm,
        pooling=config.pooling
    ).to(device)

    optimizer_cls = torch.optim.Adam if config.optimizer == "Adam" else torch.optim.AdamW
    optimizer = optimizer_cls(model.parameters(), lr=config.lr, weight_decay=config.weight_decay)

    # --------------------------------------------------
    # Training loop for this fold
    # --------------------------------------------------
    for epoch in range(config.epochs):
        model.train()
        total_loss = 0.0

        for data in train_loader:
            data = data.to(device)
            data = mask_node_features(data, 0.05)
            data = drop_edges(data, 0.1)
            optimizer.zero_grad()
            out = model(data.x, data.edge_index, data.batch)
            loss = F.cross_entropy(out, data.y)
            loss.backward()
            optimizer.step()
            total_loss += loss.item()

        train_loss = total_loss / len(train_loader)

        # Validation
        model.eval()
        val_loss, correct, total = 0.0, 0, 0
        with torch.no_grad():
            for data in val_loader:
                data = data.to(device)
                out = model(data.x, data.edge_index, data.batch)
                val_loss += F.cross_entropy(out, data.y).item()
                preds = out.argmax(dim=1)
                correct += (preds == data.y).sum().item()
                total += data.y.size(0)

        val_loss /= len(val_loader)
        val_acc = correct / total

        wandb.log({
            "fold": fold + 1,
            "epoch": epoch + 1,
            "train_loss": train_loss,
            "val_loss": val_loss,
            "val_acc": val_acc
        })

        print(
            f"Fold {fold + 1}, Epoch {epoch + 1} | "
            f"Train Loss: {train_loss:.4f} | Val Loss: {val_loss:.4f} | Val Acc: {val_acc:.4f}"
        )

    fold_results.append(val_acc)

    # Clean up between folds
    del model
    torch.cuda.empty_cache()

# --------------------------------------------------
# Summary across folds
# --------------------------------------------------
mean_acc = float(np.mean(fold_results))
std_acc = float(np.std(fold_results))

wandb.log({"mean_val_acc": mean_acc, "std_val_acc": std_acc})
print(f"\nCross-validation complete. Mean Val Acc: {mean_acc:.4f} ± {std_acc:.4f}")
wandb.finish()
